/* ============================================================
   Alpha & Omega Publications  script.js
   Author: Generated by Antigravity AI
   ============================================================ */

'use strict';

const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

/* ============================================================
   GLOBAL HISTORY & UI STATE MANAGER
   ============================================================ */
window.addEventListener('popstate', (e) => {
    // 1. Close open modals/menus
    const lightbox = document.getElementById('lightbox');
    if (lightbox && lightbox.classList.contains('open') && typeof closeLightbox === 'function') {
        closeLightbox(true);
    }
    const hamburgerBtn = document.getElementById('hamburger-btn');
    if (hamburgerBtn && hamburgerBtn.classList.contains('open') && typeof closeMenu === 'function') {
        closeMenu(true);
    }
    const orderModal = document.getElementById('order-modal');
    if (orderModal && orderModal.classList.contains('open') && typeof window.globalCloseOrderModal === 'function') {
        window.globalCloseOrderModal(true);
    }

    // 2. Restore Portfolio Filter
    if (e.state && e.state.filter && typeof applyPortfolioFilter === 'function') {
        applyPortfolioFilter(e.state.filter);
    } else if (typeof applyPortfolioFilter === 'function') {
        applyPortfolioFilter('all');
    }

    // 3. Smooth Scroll for Anchor Links (if hash is stored)
    if (e.state && e.state.hash) {
        const target = document.querySelector(e.state.hash);
        if (target) {
            const navbar = document.getElementById('navbar');
            const navHeight = navbar ? navbar.offsetHeight : 80;
            const targetPos = target.getBoundingClientRect().top + window.scrollY - navHeight;
            window.scrollTo({ top: targetPos, behavior: 'smooth' });
        }
    } else if (!window.location.hash && !e.state) {
        // If we popped to the initial page state, we can optionally scroll to top, 
        // but browser scroll restoration usually handles this nicely.
    }
});

/*  PRELOADER  */
window.addEventListener('load', () => {
    const preloader = document.getElementById('preloader');
    if (preloader) {
        setTimeout(() => preloader.classList.add('hidden'), 600);
    }
});

/*  NAVBAR SCROLL BEHAVIOR  */
const navbar = document.getElementById('navbar');
const scrollTopBtn = document.getElementById('scroll-top-btn');

window.addEventListener('scroll', () => {
    const scrollY = window.scrollY;

    // Scrolled navbar styling
    if (navbar) {
        navbar.classList.toggle('scrolled', scrollY > 60);
    }

    // Scroll-to-top button visibility
    if (scrollTopBtn) {
        scrollTopBtn.classList.toggle('show', scrollY > 400);
    }

    // Active nav link based on section
    updateActiveNavLink();
});

if (scrollTopBtn) {
    scrollTopBtn.addEventListener('click', () => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    });
}

/*  ACTIVE NAV LINK  */
function updateActiveNavLink() {
    const navLinks = Array.from(document.querySelectorAll('.nav-link'));
    const hashNavLinks = navLinks.filter(link => {
        const href = (link.getAttribute('href') || '').trim();
        return href.startsWith('#') && href.length > 1;
    });
    if (!hashNavLinks.length) return;

    const scrollY = window.scrollY + 120;
    let activeId = '';

    document.querySelectorAll('section[id]').forEach(section => {
        const top = section.offsetTop;
        const height = section.offsetHeight;
        const id = section.getAttribute('id');

        if (scrollY >= top && scrollY < top + height) {
            activeId = id || '';
        }
    });

    if (!activeId) return;
    hashNavLinks.forEach(link => {
        link.classList.toggle('active', link.getAttribute('href') === `#${activeId}`);
    });
}

/*  MOBILE MENU TOGGLE  */
const hamburgerBtn = document.getElementById('hamburger-btn');
const navLinksMenu = document.getElementById('nav-links');
const mobileOverlay = document.getElementById('mobile-overlay');

function openMenu() {
    if (!hamburgerBtn || !navLinksMenu || !mobileOverlay) return;
    hamburgerBtn.classList.add('open');
    navLinksMenu.classList.add('open');
    mobileOverlay.classList.add('show');
    hamburgerBtn.setAttribute('aria-expanded', 'true');
    document.body.style.overflow = 'hidden';
    history.pushState({ modal: 'menu' }, '', window.location.href);
}

function closeMenu(fromPopstate = false) {
    if (!hamburgerBtn || !navLinksMenu || !mobileOverlay) return;
    if (!hamburgerBtn.classList.contains('open')) return;
    hamburgerBtn.classList.remove('open');
    navLinksMenu.classList.remove('open');
    mobileOverlay.classList.remove('show');
    hamburgerBtn.setAttribute('aria-expanded', 'false');
    document.body.style.overflow = '';
}

if (hamburgerBtn) {
    hamburgerBtn.addEventListener('click', () => {
        hamburgerBtn.classList.contains('open') ? closeMenu() : openMenu();
    });
}
if (mobileOverlay) mobileOverlay.addEventListener('click', closeMenu);

// Close menu on nav link click
document.querySelectorAll('.nav-link, .nav-cta').forEach(link => {
    link.addEventListener('click', closeMenu);
});

/*  SMOOTH SCROLL FOR ANCHOR LINKS  */
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
        const targetId = this.getAttribute('href');
        if (targetId === '#') return;
        const target = document.querySelector(targetId);
        if (target) {
            e.preventDefault();
            const navHeight = navbar ? navbar.offsetHeight : 80;
            const targetPos = target.getBoundingClientRect().top + window.scrollY - navHeight;
            window.scrollTo({ top: targetPos, behavior: 'smooth' });
            
            if (history.pushState) {
                history.pushState({ hash: targetId }, '', targetId);
            }
        }
    });
});

/*  HERO PARALLAX EFFECT  */
const heroBg = document.getElementById('hero-bg');
window.addEventListener('scroll', () => {
    if (heroBg) {
        const scrollY = window.scrollY;
        heroBg.style.transform = `translateY(${scrollY * 0.3}px)`;
    }
});

/*  FLOATING PARTICLES IN HERO  */
function createParticles() {
    if (prefersReducedMotion) return;
    const container = document.getElementById('hero-particles');
    if (!container) return;
    const count = window.innerWidth < 768 ? 12 : 24;

    for (let i = 0; i < count; i++) {
        const p = document.createElement('div');
        p.className = 'particle';
        const size = Math.random() * 6 + 2;
        const left = Math.random() * 100;
        const delay = Math.random() * 12;
        const dur = Math.random() * 10 + 10;
        p.style.cssText = `
      width:${size}px; height:${size}px;
      left:${left}%; bottom:-20px;
      animation-duration:${dur}s;
      animation-delay:${delay}s;
      opacity:${Math.random() * 0.5 + 0.15};
    `;
        container.appendChild(p);
    }
}
createParticles();

/*  SCROLL-REVEAL ANIMATION  */
function initScrollReveal() {
    if (prefersReducedMotion) {
        document.querySelectorAll('[data-aos]').forEach(el => el.classList.add('visible'));
        return;
    }
    const observer = new IntersectionObserver((entries) => {
        entries.forEach((entry) => {
            if (entry.isIntersecting) {
                const delay = Array.from(entry.target.parentElement?.children || []).indexOf(entry.target);
                setTimeout(() => {
                    entry.target.classList.add('visible');
                }, delay * 90);
                observer.unobserve(entry.target);
            }
        });
    }, { threshold: 0.12, rootMargin: '0px 0px -40px 0px' });

    document.querySelectorAll('[data-aos]').forEach(el => observer.observe(el));
}
document.addEventListener('DOMContentLoaded', initScrollReveal);

/*  COUNTER ANIMATION  */
function animateCounter(el, target, duration = 1800) {
    let start = 0;
    const step = Math.ceil(target / (duration / 16));
    const timer = setInterval(() => {
        start += step;
        if (start >= target) {
            el.textContent = target.toLocaleString();
            clearInterval(timer);
        } else {
            el.textContent = start.toLocaleString();
        }
    }, 16);
}

function initCounters() {
    if (prefersReducedMotion) {
        document.querySelectorAll('.stat-num[data-target]').forEach(num => {
            num.textContent = Number.parseInt(num.dataset.target || '0', 10).toLocaleString();
        });
        return;
    }
    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                const nums = entry.target.querySelectorAll('.stat-num[data-target]');
                nums.forEach(num => {
                    animateCounter(num, parseInt(num.dataset.target));
                });
                observer.unobserve(entry.target);
            }
        });
    }, { threshold: 0.5 });

    const statsSection = document.querySelector('.hero-stats');
    if (statsSection) observer.observe(statsSection);
}
document.addEventListener('DOMContentLoaded', initCounters);

/*  PORTFOLIO FILTER  */
const filterBtns = document.querySelectorAll('.filter-btn');
const portfolioItems = document.querySelectorAll('.portfolio-item');

function applyPortfolioFilter(filter) {
    if (!filterBtns || !portfolioItems) return;
    
    // Update active button
    filterBtns.forEach(b => {
        if (b.dataset.filter === filter) {
            b.classList.add('active');
        } else {
            b.classList.remove('active');
        }
    });

    // Filter items with animation
    portfolioItems.forEach(item => {
        const categories = item.dataset.category ? item.dataset.category.split(' ') : [];
        if (filter === 'all' || categories.includes(filter)) {
            item.classList.remove('hidden');
            item.style.animation = 'fadeInUp 0.4s ease both';
        } else {
            item.classList.add('hidden');
        }
    });
}

filterBtns.forEach(btn => {
    btn.addEventListener('click', () => {
        const filter = btn.dataset.filter;
        applyPortfolioFilter(filter);
        history.pushState({ filter: filter }, '', window.location.href);
    });
});

/*  PORTFOLIO LIGHTBOX  */
const lightbox = document.getElementById('lightbox');
const lightboxImg = document.getElementById('lightbox-img');
const lightboxTitle = document.getElementById('lightbox-title');
const lightboxClose = document.getElementById('lightbox-close');
const lightboxBackdrop = document.getElementById('lightbox-backdrop');

document.querySelectorAll('.portfolio-zoom').forEach(btn => {
    btn.addEventListener('click', () => {
        if (!lightbox || !lightboxImg || !lightboxTitle) return;
        const imgSrc = btn.dataset.img;
        const title = btn.dataset.title;
        lightboxImg.src = imgSrc;
        lightboxImg.alt = title;
        lightboxTitle.textContent = title;
        lightbox.classList.add('open');
        document.body.style.overflow = 'hidden';
        history.pushState({ modal: 'lightbox' }, '', window.location.href);
    });
});

function closeLightbox(fromPopstate = false) {
    if (!lightbox || !lightboxImg || !lightbox.classList.contains('open')) return;
    lightbox.classList.remove('open');
    document.body.style.overflow = '';
    lightboxImg.src = '';
}

if (lightboxClose) lightboxClose.addEventListener('click', closeLightbox);
if (lightboxBackdrop) lightboxBackdrop.addEventListener('click', closeLightbox);
document.addEventListener('keydown', e => {
    if (e.key === 'Escape') closeLightbox();
});

/*  TESTIMONIALS SLIDER  */
function initTestimonialsSlider() {
    const track = document.getElementById('testimonial-track');
    const dotsWrap = document.getElementById('slider-dots');
    const prevBtn = document.getElementById('slider-prev');
    const nextBtn = document.getElementById('slider-next');
    if (!track) return;

    const cards = track.querySelectorAll('.testimonial-card');
    let current = 0;
    let total = 0;
    let perView = 1;

    function buildSlider() {
        perView = window.innerWidth <= 900 ? 1 : 2;
        total = Math.ceil(cards.length / perView);

        // Recreate dots
        if (dotsWrap) {
            dotsWrap.innerHTML = '';
            for (let i = 0; i < total; i++) {
                const dot = document.createElement('button');
                dot.className = 'slider-dot' + (i === 0 ? ' active' : '');
                dot.setAttribute('aria-label', `Go to slide ${i + 1}`);
                dot.addEventListener('click', () => { goTo(i); });
                dotsWrap.appendChild(dot);
            }
        }
        goTo(0);
    }

    function goTo(index) {
        if (total === 0) return;
        current = Math.max(0, Math.min(index, total - 1));
        const cardWidth = cards[0].offsetWidth + 24; // including flex gap
        const offset = current * cardWidth * perView;
        track.style.transform = `translateX(-${offset}px)`;

        if (dotsWrap) {
            dotsWrap.querySelectorAll('.slider-dot').forEach((d, i) => {
                d.classList.toggle('active', i === current);
            });
        }
    }

    if (prevBtn) {
        // clone and replace to remove old listeners just in case
        prevBtn.replaceWith(prevBtn.cloneNode(true));
        document.getElementById('slider-prev').addEventListener('click', () => { goTo(current === 0 ? total - 1 : current - 1); });
    }
    if (nextBtn) {
        nextBtn.replaceWith(nextBtn.cloneNode(true));
        document.getElementById('slider-next').addEventListener('click', () => { goTo(current === total - 1 ? 0 : current + 1); });
    }

    buildSlider();

    let resizeTimer;
    window.addEventListener('resize', () => {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(() => {
            buildSlider();
        }, 150);
    });
}
document.addEventListener('DOMContentLoaded', initTestimonialsSlider);

/*  CONTACT FORM: SERVICE PICKER ACCORDION + VALIDATION + WHATSAPP  */
const contactForm = document.getElementById('contact-form');

function validateEmail(email) {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function showError(inputId, errorId, message) {
    const input = document.getElementById(inputId);
    const error = document.getElementById(errorId);
    if (input) input.classList.add('error');
    if (error) error.textContent = message;
    return false;
}

function clearError(inputId, errorId) {
    const input = document.getElementById(inputId);
    const error = document.getElementById(errorId);
    if (input) input.classList.remove('error');
    if (error) error.textContent = '';
}

function clearAllErrors() {
    ['form-name', 'form-email', 'form-message'].forEach((id, i) => {
        clearError(id, ['err-name', 'err-email', 'err-message'][i]);
    });
    const svcErr = document.getElementById('err-service');
    if (svcErr) svcErr.textContent = '';
}

/* ---- SERVICE PICKER: accordion toggle ---- */
function initContactServicePicker() {
    const printBtn = document.getElementById('csc-printing-btn');
    const booksBtn = document.getElementById('csc-books-btn');
    const bodyPrint = document.getElementById('csc-body-printing');
    const bodyBooks = document.getElementById('csc-body-books');
    const catPrint = document.getElementById('csc-printing');
    const catBooks = document.getElementById('csc-books');
    if (!printBtn || !booksBtn) return; // not on contact page

    function toggleCat(btn, body, cat) {
        const isOpen = cat.classList.contains('csc-open');
        if (isOpen) {
            cat.classList.remove('csc-open');
            body.style.maxHeight = '0';
            btn.setAttribute('aria-expanded', 'false');
        } else {
            cat.classList.add('csc-open');
            body.style.maxHeight = body.scrollHeight + 'px';
            btn.setAttribute('aria-expanded', 'true');
        }
    }

    printBtn.addEventListener('click', () => toggleCat(printBtn, bodyPrint, catPrint));
    booksBtn.addEventListener('click', () => toggleCat(booksBtn, bodyBooks, catBooks));

    /* Live badge update on checkbox change */
    const picker = document.getElementById('service-interest-group');
    const strip = document.getElementById('csc-selected-strip');
    const badgesEl = document.getElementById('csc-badges');

    function updateBadges() {
        if (!picker || !strip || !badgesEl) return;
        const checked = Array.from(picker.querySelectorAll('input[name="contact-service"]:checked'));
        badgesEl.innerHTML = '';
        if (checked.length === 0) {
            strip.style.display = 'none';
            return;
        }
        strip.style.display = 'flex';
        checked.forEach(cb => {
            const badge = document.createElement('span');
            badge.className = 'csc-badge';
            badge.textContent = cb.value;
            badge.title = 'Click to deselect';
            badge.addEventListener('click', () => {
                cb.checked = false;
                // remove selected class from card
                const label = document.querySelector(`label[for="${cb.id}"]`);
                if (label) label.classList.remove('csc-checked');
                updateBadges();
            });
            badgesEl.appendChild(badge);
        });
        // Clear service error if any
        const svcErr = document.getElementById('err-service');
        if (svcErr && checked.length > 0) svcErr.textContent = '';
    }

    picker?.querySelectorAll('input[name="contact-service"]').forEach(cb => {
        cb.addEventListener('change', () => {
            const label = document.querySelector(`label[for="${cb.id}"]`);
            if (label) label.classList.toggle('csc-checked', cb.checked);
            // Expand the body if needed so height recalc works
            const body = cb.closest('.csc-body');
            const cat = cb.closest('.contact-service-cat');
            if (body && cat && cat.classList.contains('csc-open')) {
                body.style.maxHeight = body.scrollHeight + 'px';
            }
            updateBadges();
        });
    });
}
document.addEventListener('DOMContentLoaded', initContactServicePicker);

if (contactForm) {
    // Live validation on blur
    document.getElementById('form-name')?.addEventListener('blur', function () {
        if (this.value.trim().length < 2) {
            showError('form-name', 'err-name', 'Please enter your full name (at least 2 characters).');
        } else {
            clearError('form-name', 'err-name');
        }
    });

    document.getElementById('form-email')?.addEventListener('blur', function () {
        if (!validateEmail(this.value.trim())) {
            showError('form-email', 'err-email', 'Please enter a valid email address.');
        } else {
            clearError('form-email', 'err-email');
        }
    });

    document.getElementById('form-message')?.addEventListener('blur', function () {
        if (this.value.trim().length < 10) {
            showError('form-message', 'err-message', 'Message must be at least 10 characters long.');
        } else {
            clearError('form-message', 'err-message');
        }
    });

    contactForm.addEventListener('submit', function (e) {
        e.preventDefault();
        clearAllErrors();

        const name    = document.getElementById('form-name').value.trim();
        const email   = document.getElementById('form-email').value.trim();
        const phone   = document.getElementById('form-phone')?.value.trim() || '';
        const message = document.getElementById('form-message').value.trim();

        // Collect selected services
        const selectedServices = Array.from(
            document.querySelectorAll('input[name="contact-service"]:checked')
        ).map(cb => cb.value);

        let valid = true;

        if (name.length < 2) {
            showError('form-name', 'err-name', 'Please enter your full name (at least 2 characters).');
            valid = false;
        }
        if (!validateEmail(email)) {
            showError('form-email', 'err-email', 'Please enter a valid email address.');
            valid = false;
        }
        if (selectedServices.length === 0) {
            const svcErr = document.getElementById('err-service');
            if (svcErr) svcErr.textContent = 'Please select at least one service you are interested in.';
            valid = false;
        }
        if (message.length < 10) {
            showError('form-message', 'err-message', 'Message must be at least 10 characters long.');
            valid = false;
        }

        if (!valid) return;

        // ---- Build clean, professional WhatsApp message (invoice style) ----
        const WA_NUMBER = '233267621569';

        const contactDate = new Date().toLocaleDateString('en-GB', {
            day: 'numeric', month: 'long', year: 'numeric'
        });

        let msgRaw = '';

        // Header
        msgRaw += `🖨️ *ALPHA & OMEGA PUBLICATIONS*\n`;
        msgRaw += `_Print · Publish · Deliver_\n\n`;
        msgRaw += `📄 *PROJECT ENQUIRY*\n`;
        msgRaw += `📅 *Date :*  ${contactDate}\n\n`;

        // Contact details
        msgRaw += `👤 *CONTACT DETAILS*\n`;
        msgRaw += `  Name  :  ${name}\n`;
        msgRaw += `  Email :  ${email}\n`;
        if (phone) {
            let fp = phone.replace(/[^\d+]/g, '');
            if (fp.startsWith('0')) fp = '+233' + fp.slice(1);
            else if (!fp.startsWith('+')) fp = '+' + fp;
            msgRaw += `  Phone :  ${fp}\n`;
        }
        msgRaw += `\n`;

        // Services interested in
        msgRaw += `🖨️ *SERVICE(S) INTERESTED IN*\n`;
        selectedServices.forEach((s, idx) => {
            msgRaw += `  ${idx + 1}. ${s}\n`;
        });
        msgRaw += `\n`;

        // Project details
        msgRaw += `💬 *PROJECT DETAILS*\n`;
        msgRaw += `  ${message}\n\n`;

        // Footer
        msgRaw += `Thank you for reaching out. We will be in touch shortly.\n`;
        msgRaw += `_Sent via alphaandomegapublications.com_`;

        const waMsg = encodeURIComponent(msgRaw);

        const submitBtn = document.getElementById('form-submit');
        const successEl = document.getElementById('form-success');

        submitBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Opening WhatsApp...';
        submitBtn.disabled = true;

        setTimeout(() => {
            window.open(`https://wa.me/${WA_NUMBER}?text=${waMsg}`, '_blank');
            submitBtn.innerHTML = '<i class="fab fa-whatsapp"></i> Send via WhatsApp';
            submitBtn.disabled = false;
            contactForm.reset();
            // Reset picker UI
            document.querySelectorAll('input[name="contact-service"]').forEach(cb => cb.checked = false);
            document.querySelectorAll('.csc-option').forEach(lbl => lbl.classList.remove('csc-checked'));
            const strip = document.getElementById('csc-selected-strip');
            if (strip) strip.style.display = 'none';
            clearAllErrors();
            if (successEl) {
                successEl.classList.add('show');
                setTimeout(() => successEl.classList.remove('show'), 7000);
            }
        }, 800);
    });
}


/*  ABOUT PAGE: CITATION LIGHTBOX  */
function initAboutCitationLightbox() {
    const lightbox = document.getElementById('citation-lightbox');
    const trigger = document.querySelector('.citations-open-book');
    if (!lightbox || !trigger) return;

    const closeBtn = lightbox.querySelector('.lightbox-close');
    const content = lightbox.querySelector('.lightbox-dual-content');

    const open = () => {
        lightbox.classList.add('show');
        document.body.style.overflow = 'hidden';
    };
    const close = () => {
        lightbox.classList.remove('show');
        document.body.style.overflow = '';
    };

    trigger.addEventListener('click', open);
    trigger.addEventListener('keydown', e => {
        if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            open();
        }
    });
    lightbox.addEventListener('click', close);
    content?.addEventListener('click', e => e.stopPropagation());
    closeBtn?.addEventListener('click', close);
    document.addEventListener('keydown', e => {
        if (e.key === 'Escape' && lightbox.classList.contains('show')) close();
    });
}
document.addEventListener('DOMContentLoaded', initAboutCitationLightbox);

/*  PORTFOLIO PAGE: IMAGE STAGE ROTATOR  */
function initPortfolioStageRotator() {
    const designImg = document.getElementById('portfolio-design-img');
    const prepressImg = document.getElementById('portfolio-prepress-img');
    const finishImg = document.getElementById('portfolio-finish-img');
    if (!designImg || !prepressImg || !finishImg) return;

    if (prefersReducedMotion) return;

    const rotate = (el, frames, delay) => {
        let index = 0;
        setInterval(() => {
            index = (index + 1) % frames.length;
            el.classList.remove('pop-anim');
            void el.offsetWidth;
            el.src = frames[index];
            el.classList.add('pop-anim');
        }, delay);
    };

    rotate(designImg, ['design1.jpg', 'design_consult1.jpg', 'design_consult2.jpg', 'design_consult3.jpg', 'design_consult4.jpg'], 3200);
    rotate(prepressImg, ['prepress1.jpg', 'prepress2.jpg', 'prepress3.jpg', 'prepress4.jpg', 'prepress5.jpg'], 3600);
    rotate(finishImg, ['finalp.jpg', 'finalp_new1.jpg', 'finalp_new2.jpg'], 3800);
}
document.addEventListener('DOMContentLoaded', initPortfolioStageRotator);

/*  SERVICES PAGE: PANEL CONTROLS  */
function initServiceCategoryControls() {
    const btnPrint = document.getElementById('btn-printing');
    const btnBooks = document.getElementById('btn-books');
    const printSection = document.getElementById('printing-section');
    const booksSection = document.getElementById('books-section');
    if (!btnPrint || !btnBooks || !printSection || !booksSection) return;

    const onAction = (target) => {
        if (target === 'printing') switchServiceCategory('printing');
        if (target === 'books') switchServiceCategory('books');
    };

    btnPrint.addEventListener('click', () => onAction('printing'));
    btnBooks.addEventListener('click', () => onAction('books'));
    btnPrint.addEventListener('keydown', e => {
        if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            onAction('printing');
        }
    });
    btnBooks.addEventListener('keydown', e => {
        if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            onAction('books');
        }
    });
}
document.addEventListener('DOMContentLoaded', initServiceCategoryControls);
/*  FOOTER YEAR  */
const yearEl = document.getElementById('footer-year');
if (yearEl) yearEl.textContent = new Date().getFullYear();

/*  SERVICE CARD TILT EFFECT  */
function initTiltEffect() {
    if (prefersReducedMotion) return;
    document.querySelectorAll('.service-card, .why-card').forEach(card => {
        card.addEventListener('mousemove', (e) => {
            const rect = card.getBoundingClientRect();
            const x = e.clientX - rect.left - rect.width / 2;
            const y = e.clientY - rect.top  - rect.height / 2;
            const tiltX = (-y / rect.height * 8).toFixed(2);
            const tiltY = ( x / rect.width  * 8).toFixed(2);
            card.style.transform = `perspective(800px) rotateX(${tiltX}deg) rotateY(${tiltY}deg) translateY(-6px)`;
        });
        card.addEventListener('mouseleave', () => {
            card.style.transform = '';
        });
    });
}
document.addEventListener('DOMContentLoaded', initTiltEffect);

/*  MARQUEE PAUSE ON HOVER  */
const marqueeTrack = document.querySelector('.marquee-track');
if (marqueeTrack) {
    marqueeTrack.addEventListener('mouseenter', () => { marqueeTrack.style.animationPlayState = 'paused'; });
    marqueeTrack.addEventListener('mouseleave', () => { marqueeTrack.style.animationPlayState = 'running'; });
}

/*  KEYBOARD ACCESSIBILITY + MODAL CLOSE  */
document.addEventListener('keydown', e => {
    if (e.key !== 'Escape') return;
    // Close mobile nav menu
    if (navLinksMenu?.classList.contains('open')) closeMenu();
    // Close order success modal (delegates to the order platform handler)
    const orderModal = document.getElementById('order-modal');
    if (orderModal?.classList.contains('open')) {
        if (typeof window.globalCloseOrderModal === 'function') {
            window.globalCloseOrderModal(true);
        } else {
            orderModal.classList.remove('open');
            document.body.style.overflow = '';
        }
    }
});

/* ============================================================
   SERVICES PAGE: SWITCH SERVICE CATEGORY
   ============================================================ */
function switchServiceCategory(category) {
    const printSection = document.getElementById('printing-section');
    const booksSection = document.getElementById('books-section');
    const btnPrint = document.getElementById('btn-printing');
    const btnBooks = document.getElementById('btn-books');

    if (!printSection || !booksSection) return;

    const navHeight = document.getElementById('navbar') ? document.getElementById('navbar').offsetHeight : 80;

    if (category === 'printing') {
        printSection.style.display = 'block';
        setTimeout(() => printSection.classList.add('active'), 50);
        booksSection.style.display = 'none';
        booksSection.classList.remove('active');

        btnPrint.classList.add('active-split');
        btnBooks.classList.remove('active-split');

        setTimeout(() => {
            const targetPos = printSection.getBoundingClientRect().top + window.scrollY - navHeight - 30;
            window.scrollTo({ top: targetPos, behavior: 'smooth' });
        }, 300);

    } else if (category === 'books') {
        booksSection.style.display = 'block';
        setTimeout(() => booksSection.classList.add('active'), 50);
        printSection.style.display = 'none';
        printSection.classList.remove('active');

        btnBooks.classList.add('active-split');
        btnPrint.classList.remove('active-split');

        setTimeout(() => {
            const targetPos = booksSection.getBoundingClientRect().top + window.scrollY - navHeight - 30;
            window.scrollTo({ top: targetPos, behavior: 'smooth' });
        }, 300);
    }
}



